# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='userName',
            field=models.CharField(default='title', max_length=32),
        ),
    ]
